### ISSUE TITLE
HTTParty Crashing with Invalid URI in Gitlab

### ISSUE THREAD

**Issue by dsalaza4** [danger/danger.systems#118]
Hi, I recently implemented Danger-ruby in one of my company's Gitlab repos. 
Sometimes, when runing Danger checks after a MR is created, it fails with the following log
```
$ bundle exec danger --verbose --fail-on-errors=true
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://gitlab.com/api/v4/projects/fluidattacks%2Fwriteups/merge_requests/316 (URI::InvalidURIError)
318
	from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.3/lib/httparty/request.rb:75:in `path='
	from /var/lib/gems/2.3.0/gems/httparty-0.16.3/lib/httparty/request.rb:65:in `initialize'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.3/lib/httparty.rb:573:in `new'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.3/lib/httparty.rb:573:in `perform_request'
	from /var/lib/gems/2.3.0/gems/httparty-0.16.3/lib/httparty.rb:491:in `get'
	from /var/lib/gems/2.3.0/gems/gitlab-4.8.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.3.0/gems/gitlab-4.8.0/lib/gitlab/client/merge_requests.rb:43:in `merge_request'
	from /var/lib/gems/2.3.0/gems/danger-5.11.1/lib/danger/request_sources/gitlab.rb:104:in `fetch_details'
	from /var/lib/gems/2.3.0/gems/danger-5.11.1/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
	from /var/lib/gems/2.3.0/gems/danger-5.11.1/lib/danger/danger_core/dangerfile.rb:266:in `run'
	from /var/lib/gems/2.3.0/gems/danger-5.11.1/lib/danger/danger_core/executor.rb:28:in `run'
	from /var/lib/gems/2.3.0/gems/danger-5.11.1/lib/danger/commands/runner.rb:70:in `run'
	from /var/lib/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.3.0/gems/danger-5.11.1/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:22:in `load'
	from /usr/local/bin/danger:22:in `<main>'
ERROR: Job failed: exit code 1
```

After a short google search, I found this: https://github.com/jnunemaker/httparty/issues/180
Hence, I am suspecting the issue is related to the fact that sometimes (I can't tell what triggers it) Danger is not correctly escaping the "/" characters (Notice how in the log, only one of the "/" was escaped to "%2F").
I am unable to fix this as such string is totally managed by Danger's internal scripts :/

**Comment by dsalaza4** [comment]
Moving this issue to https://gitlab.com/danger-systems/danger.systems/issues/121
